general:
  title: Dima Glushkov
  favicon: /assets/favicon.ico
  
  name: Dima
  surname: Glushkov
  photo_url: /assets/profile_photo.jpg
  bio: 22 y.o. software engineer, open-source & linux enthusiast
  location: Saint-Petersburg, Russia

contacts:
  - icon: "fab fa-github"
    url_text: "@dimaglushkov"
    url: https://github.com/dimaglushkov
  - icon: "fab fa-telegram"
    url_text: "@dimaglushkov"
    url: https://t.me/dimaglushkov
  - icon: "fa-brands fa-linkedin"
    url_text: "@dimaglushkov"
    url: https://www.linkedin.com/in/dimaglushkov/
  - icon: "fa-solid fa-at"
    url_text: ddimaglushkov@ya.ru
    url: "mailto:ddimaglushkov@ya.ru"


cv:
  education:
    - since: "2005"
      till: "2014"
      place: "Gymnasium named after F.K. Salmanov, Surgut"
    - since: "2014"
      till: "2017"
      place: "School №547, Saint-Petersburg"
      note: "finished with a gold medal"
    - since: "2017"
      till: "2021"
      place: "ITMO University, Saint-Petersburg"
      note: "\"System and applied software\", software engineering"

  pub:
    - event: "X Congress of Young Scientists"
      theme: "Research on employment processes in the field of IT"

  exp:
    - since: "feb 2020"
      till: "jun 2021"
      place: "online-cinema Okko"
      position: "product analyst"
    - since: "jul 2021"
      till: "jan 2022"
      place: "local startup"
      position: "Go backend-developer & system architect"

  certs:
    - link: /assets/huawei-cert.pdf
      desc: "Huawei \"Routing & Switching\" certificate"

  skills:
    - desc: "Great experience with linux-based systems"
    - desc: "Todo: fill this list"

projects:
  - name: checkers online
    img_url: https://raw.githubusercontent.com/dimaglushkov/checkers-online/master/Client/img/samples/game.png
    code_url: https://github.com/dimaglushkov/checkers-online
    description: Client-server implementation of well-known checkers written on C with SDL2.0 for GUI
    tags: c, sdl2.0, cmake, client-server, low-level programming

  - name: lightdm webkit 2 minimal theme
    img_url: https://github.com/allacee/lightdm-webkit2-theme-minimal/raw/master/assets/screenshots/screenshot-2.png
    code_url: https://github.com/dimaglushkov/lightdm-webkit2-theme-minimal
    description: Minimalistic theme for a lightdm display manager with a webkit2 greeter
    tags: js, css, linux

  - name: visual sorting
    img_url: https://raw.githubusercontent.com/dimaglushkov/visual-sorting/master/sample.png
    code_url: https://github.com/dimaglushkov/visual-sorting
    demo_url: https://sort.dimaglushkov.xyz
    description: Broswer app to visualize most popular sorting algorithms
    tags: js, css, algorithms

  - name: dotfiles
    img_url: https://github.com/dimaglushkov/dotfiles/blob/main/assets/screenshots/screen-sample-1.png?raw=true
    code_url: https://github.com/dimaglushkov/dotfiles
    description: Repository with my own builds of dwm, dwmblocks, etc. Also contains a lot of self-written bash-scripts
    tags: linux, bash, manjaro

  - name: forthnight
    img_url: /assets/forthnight.png
    code_url: https://github.com/dimaglushkov/forthnight
    description: Repository with my own builds of dwm, dwmblocks, etc. Also contains a lot of self-written bash-scripts
    tags: c, asm, forth, low-level programming

  - name: and even more...
    description: you could find more projects on my github page!