general:
  title: Dima Glushkov
  favicon: /assets/favicon.ico

  name: Dima
  surname: Glushkov
  photo_url: 
  about: 22 y.o. software engineer, open-source & linux enthusiast
  location: Saint-Petersburg, Russia

  contacts:
    github: https://github.com/dimaglushkov
    telegram: "@dimaglushkov"
    email: ddimaglushkov@ya.ru
    linkedin: https://www.linkedin.com/in/dimaglushkov/


projects:
  - name: Checkers online
    img_url: ""
    code_url: https://github.com/dimaglushkov/checkers-online
    description: Шашки

  - name: Lightdm webkit 2 minimal theme
    img_url: ""
    code_url: https://github.com/dimaglushkov/lightdm-webkit2-theme-minimal
    description: Simple theme for a lightdm display manager with a webkit2 greeter.